language: python

jobs:  
  include:
    - stage: "Tests"
      name: "Unit Tests"
      python: "3.6"
      script: 
        - make test  
    - stage: Publish
      name: "Publish to pypi"
      python: "3.6"
      # if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - make publish
